@echo off
"C:\laragon\www\_utils\avifenc\avifenc.exe" --ignore-xmp --ignore-exif --ignore-profile --ignore-icc -q 92 -s 4 -y 444 -a end-usage=q -a cq-level=36 -a tune=ssim -a color:sharpness=0 -a color:enable-chroma-deltaq=1 -a color:enable-qm=1 -a color:deltaq-mode=3 %~1 %~2
exit /b %errorlevel%